# Auto Generated Dockerfile

FROM ballerina/ballerina:0.981.1
LABEL maintainer="dev@ballerina.io"

COPY vehicle_rest_service.balx /home/ballerina 

EXPOSE  9090

CMD ballerina run vehicle_rest_service.balx
