ALTER TABLE `AM_APPLICATION` ADD COLUMN `APPLICATION_TIER` VARCHAR(50) DEFAULT 'Unlimited'  AFTER `SUBSCRIBER_ID`;
CREATE TABLE IF NOT EXISTS AM_API_URL_MAPPING (
    URL_MAPPING_ID INTEGER AUTO_INCREMENT,
    API_ID INTEGER NOT NULL,
    HTTP_METHOD VARCHAR(20) NULL,
    AUTH_SCHEME VARCHAR(50) NULL,
    URL_PATTERN VARCHAR(512) NULL,
    PRIMARY KEY(URL_MAPPING_ID)
);
