DROP TABLE IF EXISTS API_DESTINATION_SUMMARY;
DROP SEQUENCE IF EXISTS API_DESTINATION_SUMMARY_PK_SEQ;
CREATE SEQUENCE API_DESTINATION_SUMMARY_PK_SEQ;
CREATE TABLE API_DESTINATION_SUMMARY (
  API VARCHAR(100) NOT NULL DEFAULT '',
  VERSION VARCHAR(100) NOT NULL DEFAULT '',
  APIPUBLISHER VARCHAR(100) NOT NULL DEFAULT '',
  CONTEXT VARCHAR(100) NOT NULL DEFAULT '',
  DESTINATION VARCHAR(100) NOT NULL DEFAULT '',
  TOTAL_REQUEST_COUNT INTEGER DEFAULT NULL,
  HOSTNAME VARCHAR(100) NOT NULL DEFAULT '',
  YEAR SMALLINT DEFAULT NULL,
  MONTH SMALLINT DEFAULT NULL,
  DAY SMALLINT DEFAULT NULL,
  TIME VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (API,VERSION,APIPUBLISHER,CONTEXT,DESTINATION,HOSTNAME,TIME)
);

DROP TABLE IF EXISTS API_FAULT_SUMMARY;
DROP SEQUENCE IF EXISTS API_FAULT_SUMMARY_PK_SEQ;
CREATE SEQUENCE API_FAULT_SUMMARY_PK_SEQ;
CREATE TABLE API_FAULT_SUMMARY (
  API VARCHAR(100) NOT NULL DEFAULT '',
  VERSION VARCHAR(100) NOT NULL DEFAULT '', 
  APIPUBLISHER VARCHAR(100) NOT NULL DEFAULT '',
  CONSUMERKEY VARCHAR(100) DEFAULT NULL,
  CONTEXT VARCHAR(100) NOT NULL DEFAULT '',
  TOTAL_FAULT_COUNT INTEGER DEFAULT NULL,
  HOSTNAME VARCHAR(100) NOT NULL DEFAULT '',
  YEAR SMALLINT DEFAULT NULL,
  MONTH SMALLINT DEFAULT NULL,
  DAY SMALLINT DEFAULT NULL,
  TIME VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (API,VERSION,APIPUBLISHER,CONTEXT,HOSTNAME,TIME)
); 

DROP TABLE IF EXISTS API_REQUEST_SUMMARY;
DROP SEQUENCE IF EXISTS API_REQUEST_SUMMARY_PK_SEQ;
CREATE SEQUENCE API_REQUEST_SUMMARY_PK_SEQ;
CREATE TABLE API_REQUEST_SUMMARY (
  API VARCHAR(100) NOT NULL DEFAULT '',
  API_VERSION VARCHAR(100) NOT NULL DEFAULT '',
  VERSION VARCHAR(100) NOT NULL DEFAULT '',
  APIPUBLISHER VARCHAR(100) NOT NULL DEFAULT '',
  CONSUMERKEY VARCHAR(100) NOT NULL DEFAULT '',
  USERID VARCHAR(100) NOT NULL DEFAULT '',
  CONTEXT VARCHAR(100) NOT NULL DEFAULT '',
  MAX_REQUEST_TIME BIGINT DEFAULT NULL,
  TOTAL_REQUEST_COUNT INTEGER DEFAULT NULL,
  HOSTNAME VARCHAR(100) NOT NULL DEFAULT '',
  YEAR SMALLINT DEFAULT NULL,
  MONTH SMALLINT DEFAULT NULL,
  DAY SMALLINT DEFAULT NULL,
  TIME VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (API,API_VERSION,VERSION,APIPUBLISHER,CONSUMERKEY,USERID,CONTEXT,HOSTNAME,TIME)
); 

DROP TABLE IF EXISTS API_RESOURCE_USAGE_SUMMARY;
DROP SEQUENCE IF EXISTS API_RESOURCE_USAGE_SUMMARY_PK_SEQ;
CREATE SEQUENCE API_RESOURCE_USAGE_SUMMARY_PK_SEQ;
CREATE TABLE API_RESOURCE_USAGE_SUMMARY (
  API VARCHAR(100) NOT NULL DEFAULT '',
  VERSION VARCHAR(100) NOT NULL DEFAULT '',
  APIPUBLISHER VARCHAR(100) NOT NULL DEFAULT '',
  CONSUMERKEY VARCHAR(100) NOT NULL DEFAULT '',
  RESOURCEPATH VARCHAR(100) NOT NULL DEFAULT '',
  CONTEXT VARCHAR(100) NOT NULL DEFAULT '',
  METHOD VARCHAR(100) NOT NULL DEFAULT '',
  TOTAL_REQUEST_COUNT INTEGER DEFAULT NULL,
  HOSTNAME VARCHAR(100) NOT NULL DEFAULT '',
  YEAR SMALLINT DEFAULT NULL,
  MONTH SMALLINT DEFAULT NULL,
  DAY SMALLINT DEFAULT NULL,
  TIME VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (API,VERSION,APIPUBLISHER,CONSUMERKEY,CONTEXT,RESOURCEPATH,METHOD,HOSTNAME,TIME)
); 

DROP TABLE IF EXISTS API_RESPONSE_SUMMARY;
DROP SEQUENCE IF EXISTS API_RESPONSE_SUMMARY_PK_SEQ;
CREATE SEQUENCE API_RESPONSE_SUMMARY_PK_SEQ;
CREATE TABLE API_RESPONSE_SUMMARY (
  API_VERSION VARCHAR(100) NOT NULL DEFAULT '',
  APIPUBLISHER VARCHAR(100) NOT NULL DEFAULT '',
  CONTEXT VARCHAR(100) NOT NULL DEFAULT '',
  SERVICETYPE INTEGER DEFAULT NULL,
  TOTAL_RESPONSE_COUNT INTEGER DEFAULT NULL,
  HOSTNAME VARCHAR(100) NOT NULL DEFAULT '',
  YEAR SMALLINT DEFAULT NULL,
  MONTH SMALLINT DEFAULT NULL,
  DAY SMALLINT DEFAULT NULL,
  TIME VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (API_VERSION,APIPUBLISHER,CONTEXT,HOSTNAME,TIME)
); 

DROP TABLE IF EXISTS API_VERSION_USAGE_SUMMARY;
DROP SEQUENCE IF EXISTS API_VERSION_USAGE_SUMMARY_PK_SEQ;
CREATE SEQUENCE API_VERSION_USAGE_SUMMARY_PK_SEQ;
CREATE TABLE API_VERSION_USAGE_SUMMARY (
  API VARCHAR(100) NOT NULL DEFAULT '',
  VERSION VARCHAR(100) NOT NULL DEFAULT '',
  APIPUBLISHER VARCHAR(100) NOT NULL DEFAULT '',
  CONTEXT VARCHAR(100) NOT NULL DEFAULT '',
  TOTAL_REQUEST_COUNT INTEGER DEFAULT NULL,
  HOSTNAME VARCHAR NOT NULL DEFAULT '',
  YEAR SMALLINT DEFAULT NULL,
  MONTH SMALLINT DEFAULT NULL,
  DAY SMALLINT DEFAULT NULL,
  TIME VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (API,VERSION,APIPUBLISHER,CONTEXT,HOSTNAME,TIME)
); 

DROP TABLE IF EXISTS API_THROTTLED_OUT_SUMMARY;
DROP SEQUENCE IF EXISTS API_THROTTLED_OUT_SUMMARY_PK_SEQ;
CREATE SEQUENCE API_THROTTLED_OUT_SUMMARY_PK_SEQ;
CREATE TABLE API_THROTTLED_OUT_SUMMARY (
  API VARCHAR(100) NOT NULL DEFAULT '',
  API_VERSION VARCHAR(100) NOT NULL DEFAULT '',
  CONTEXT VARCHAR(100) NOT NULL DEFAULT '',
  APIPUBLISHER VARCHAR(100) NOT NULL DEFAULT '',
  APPLICATIONNAME VARCHAR(100) NOT NULL DEFAULT '',
  TENANTDOMAIN VARCHAR(100) NOT NULL DEFAULT '',
  YEAR SMALLINT DEFAULT NULL,
  MONTH SMALLINT DEFAULT NULL,
  DAY SMALLINT DEFAULT NULL,
  WEEK INTEGER DEFAULT NULL,
  TIME VARCHAR(30) NOT NULL DEFAULT '',
  SUCCESS_REQUEST_COUNT INTEGER DEFAULT NULL,
  THROTTLEOUT_COUNT INTEGER DEFAULT NULL,
  PRIMARY KEY (API,API_VERSION,CONTEXT,APIPUBLISHER,APPLICATIONNAME,TENANTDOMAIN,YEAR,MONTH,DAY,TIME)
);

DROP TABLE IF EXISTS API_LAST_ACCESS_TIME_SUMMARY;
DROP SEQUENCE IF EXISTS API_LAST_ACCESS_TIME_SUMMARY_PK_SEQ;
CREATE SEQUENCE API_LAST_ACCESS_TIME_SUMMARY_PK_SEQ;
CREATE TABLE API_LAST_ACCESS_TIME_SUMMARY (
  TENANTDOMAIN VARCHAR(100) NOT NULL DEFAULT '',
  APIPUBLISHER VARCHAR(100) NOT NULL DEFAULT '',
  API VARCHAR(100) NOT NULL DEFAULT '',
  VERSION VARCHAR(100) DEFAULT NULL,
  USERID VARCHAR(100) DEFAULT NULL,
  CONTEXT VARCHAR(100) DEFAULT NULL,
  MAX_REQUEST_TIME BIGINT DEFAULT NULL,
  PRIMARY KEY (TENANTDOMAIN,APIPUBLISHER,API)
);

