Feature: AI Design Assistant default implementation — backend invocation
  Exercises the out-of-the-box (default) Design Assistant implementation end-to-end against a canned AI backend
  (carbon-apimgt PR #13920). The block overlay points [apim.ai] endpoint at the node stub
  (http://nodebackend:3001/ai/...) with an auth token set, so DefaultDesignAssistantServiceImpl performs a real
  HTTP call to the AI service and the Publisher REST layer maps the response back to the client. Proves the
  default code path (config resolution, factory, HTTP invocation, response mapping) works after the
  pluggable-implementation refactor.

  Background:
    Given The system is ready and I have valid publisher access tokens as "publisherUser"

  @cap:publisher @feat:design-assistant @rule:default-impl @type:smoke
  Scenario: Design Assistant generate-payload returns the AI service payload
    When I put the following JSON payload in context as "daGenSession"
      """
      { "sessionId": "integration-v2-session" }
      """
    And I send an AI Design Assistant generate-payload request with payload "daGenSession"
    Then The response status code should be 200
    And The response should contain "Mock design payload generated by the AI stub"

  @cap:publisher @feat:design-assistant @rule:default-impl @type:smoke
  Scenario: Design Assistant chat returns the AI service response
    When I put the following JSON payload in context as "daChatSession"
      """
      { "sessionId": "integration-v2-session", "text": "Design an API for a pet store" }
      """
    And I send an AI Design Assistant chat request with payload "daChatSession"
    Then The response status code should be 200
    And The response should contain "Mock design assistant chat response"
