/*
* Copyright 2004,2005 The Apache Software Foundation.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package org.wso2.am.integration.services.jaxrs.coffeesample.bean;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "PaymentStatus")
public class PaymentStatus {

	/**
	 * If XmlElement wasn't there, the generated element name will be simple letters, 'status'
	 * Here, we modified it to 'Status'
	 * <p/>
	 * name is of type String, and required is of type boolean
	 * <p/>
	 * Since the required attribute is set to true, no get method for this variable
	 */
	@XmlElement(name = "Status", required = true)
	private String status;

	/**
	 * Since Payment class is also a bean, the JSON content generated by this bean
	 * will be wrapped in to PaymentStatus bean
	 * ex.
	 * {
	 * "PaymentStatus":
	 * {
	 * "Payment":{"amount":50,"cardNumber":"1234 2345 3456 4567","expiryDate":"01-01-2015","name":"Kasun Gajasinghe"},
	 * "Status":"Payment Accepted"
	 * }
	 * }
	 */
	@XmlElement(name = "Payment", required = true)
	private Payment payment;

	public PaymentStatus(String status, Payment payment) {
		this.setStatus(status);
		this.setPayment(payment);
	}

	/**
	 * A no-arg default constructor is needed for proper operation of JAX-RS
	 */
	public PaymentStatus() {

	}

	//    public String getStatus() {
	//        return status;
	//    }
	//
	//    public Payment getPayment() {
	//        return payment;
	//    }

	public void setStatus(String status) {
		this.status = status;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}
}
