ALTER TABLE AM_APPLICATION ADD UUID VARCHAR(256);
ALTER TABLE AM_APPLICATION ADD CONSTRAINT AM_APP_UUID_UNIQUE unique(UUID);
ALTER TABLE AM_SUBSCRIPTION ADD UUID VARCHAR(256) ;
ALTER TABLE AM_SUBSCRIPTION ADD CONSTRAINT AM_SUB_UUID_UNIQUE unique(UUID);