ALTER TABLE AM_APPLICATION ADD UUID VARCHAR(256);
UPDATE AM_APPLICATION SET UUID = NEWID() WHERE UUID IS NULL;
ALTER TABLE AM_APPLICATION ADD UNIQUE (UUID);
ALTER TABLE AM_SUBSCRIPTION ADD UUID VARCHAR(256);
UPDATE AM_SUBSCRIPTION SET UUID = NEWID() WHERE UUID IS NULL;
ALTER TABLE AM_SUBSCRIPTION ADD UNIQUE (UUID);