ALTER TABLE AM_APPLICATION ADD UUID VARCHAR(256) UNIQUE;
UPDATE AM_APPLICATION SET UUID = md5(random()::text || clock_timestamp()::text)::uuid WHERE UUID IS NULL;
ALTER TABLE AM_SUBSCRIPTION ADD UUID VARCHAR(256) UNIQUE;
UPDATE AM_SUBSCRIPTION SET UUID = md5(random()::text || clock_timestamp()::text)::uuid WHERE UUID IS NULL;
