site_name: APIM Test Framework
nav:
  - Home: index.md
  - For Test Writers:
      - Getting Started: users/getting-started.md
      - Writing Integration Tests:
          - Steps Related to Container Initialzation: users/Writing-tests/container-init-steps.md
          - Step Related to Publisher: users/Writing-tests/publisher-steps.md
          - Step Related to Store: users/Writing-tests/store-steps.md 
          - Step Related to API Invocation: users/Writing-tests/API-Invoc-steps.md
  - For Framework Developers:
      - Architecture Overview: devs/architecture.md
      - Code Structure: devs/code-structure.md
      - Extending the Framework: devs/extending.md
      - Contribution Guide: devs/contributing.md
  - Changelog: changelog.md
theme:
  name: mkdocs
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - attr_list
