SELECT constraint_name FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_SCHEMA = database() and TABLE_NAME = "IDN_OAUTH1A_REQUEST_TOKEN" and referenced_column_name is not NULL limit 1;
ALTER TABLE IDN_OAUTH1A_REQUEST_TOKEN DROP FOREIGN KEY <temp_key_name>;
{}
SELECT constraint_name FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_SCHEMA = database() and TABLE_NAME = "IDN_OAUTH1A_ACCESS_TOKEN" and referenced_column_name is not NULL limit 1;
ALTER TABLE IDN_OAUTH1A_ACCESS_TOKEN DROP FOREIGN KEY <temp_key_name>;
{}
SELECT constraint_name FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_SCHEMA = database() and TABLE_NAME = "IDN_OAUTH2_ACCESS_TOKEN" and referenced_column_name is not NULL limit 1;
ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN DROP FOREIGN KEY <temp_key_name>;
{}
SELECT constraint_name FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_SCHEMA = database() and TABLE_NAME = "IDN_OAUTH2_AUTHORIZATION_CODE" and referenced_column_name is not NULL limit 1;
ALTER TABLE IDN_OAUTH2_AUTHORIZATION_CODE DROP FOREIGN KEY <temp_key_name>;
{}
SHOW COLUMNS FROM IDN_OAUTH_CONSUMER_APPS LIKE "ID";
ALTER TABLE IDN_OAUTH_CONSUMER_APPS DROP PRIMARY KEY;
ALTER TABLE IDN_OAUTH_CONSUMER_APPS ADD ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE IDN_OAUTH_CONSUMER_APPS MODIFY COLUMN CONSUMER_KEY VARCHAR (255)  NOT NULL;
ALTER TABLE IDN_OAUTH_CONSUMER_APPS ADD CONSTRAINT CONSUMER_KEY_CONSTRAINT UNIQUE (CONSUMER_KEY);
{}

ALTER TABLE IDN_OAUTH1A_REQUEST_TOKEN ADD CONSUMER_KEY_ID INTEGER;
UPDATE IDN_OAUTH1A_REQUEST_TOKEN REQUEST_TOKEN set REQUEST_TOKEN.CONSUMER_KEY_ID = (select CONSUMER_APPS.ID from IDN_OAUTH_CONSUMER_APPS CONSUMER_APPS where CONSUMER_APPS.CONSUMER_KEY = REQUEST_TOKEN.CONSUMER_KEY);
ALTER TABLE IDN_OAUTH1A_REQUEST_TOKEN DROP COLUMN CONSUMER_KEY;
ALTER TABLE IDN_OAUTH1A_REQUEST_TOKEN ADD FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE;

