[server]
#hostname = "km.wso2.com"
server_role = "api-key-manager-deprecated"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "mysql"
hostname = "apim.mysql"
name = "apimgt_db"
port = "3306"
username = "apimuser"
password = "apimuser"

[database.shared_db]
type = "mysql"
hostname = "shared_db.mysql"
name = "shared_db"
port = "3306"
username = "shareduser"
password = "shareduser"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"


[[event_handler]]
name="userPostSelfRegistration"
subscriptions=["POST_ADD_USER"]

[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1
[event_listener.properties]
notification_endpoint = "https://tm.wso2.com:443/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "default"

# Traffic Manager configurations
[apim.throttling]
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
throttle_decision_endpoints = ["tcp://tm1.local:5672","tcp://tm2.local:5672"]

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://tm1.local:9611"]
traffic_manager_auth_urls=["ssl://tm1.local:9711"]

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://tm2.local:9611"]
traffic_manager_auth_urls=["ssl://tm2.local:9711"]