[server]
#hostname = "tm.wso2.com"
server_role = "traffic-manager"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
hostname = "shared_db.mysql"
name = "shared_db"
port = "3306"
username = "shareduser"
password = "shareduser"

[database.apim_db]
type = "mysql"
hostname = "apim.mysql"
name = "apimgt_db"
port = "3306"
username = "apimuser"
password = "apimuser"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

# key manager implementation
[apim.key_manager]
service_url = "https://km.wso2.com:443/services/"

[apim.oauth_config]
revoke_endpoint = "https://km.wso2.com:9443/oauth2/revoke"
enable_token_encryption = false
enable_token_hashing = false