/*
 * WSO2 API Manager - Publisher API
 * This specifies a **RESTful API** for WSO2 **API Manager** - Publisher.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.am.integration.clients.publisher.api.v1;

import org.wso2.am.integration.clients.publisher.api.ApiException;
import org.wso2.am.integration.clients.publisher.api.v1.dto.APIMonetizationInfoDTO;
import org.wso2.am.integration.clients.publisher.api.v1.dto.APIMonetizationUsageDTO;
import org.wso2.am.integration.clients.publisher.api.v1.dto.APIRevenueDTO;
import org.wso2.am.integration.clients.publisher.api.v1.dto.ErrorDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiMonetizationApi
 */
@Ignore
public class ApiMonetizationApiTest {

    private final ApiMonetizationApi api = new ApiMonetizationApi();

    
    /**
     * Get monetization status for each tier in a given API
     *
     * This operation can be used to get monetization status for each tier in a given API 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apisApiIdMonetizationGetTest() throws ApiException {
        String apiId = null;
        api.apisApiIdMonetizationGet(apiId);

        // TODO: test validations
    }
    
    /**
     * Configure monetization for a given API
     *
     * This operation can be used to configure monetization for a given API. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apisApiIdMonetizePostTest() throws ApiException {
        String apiId = null;
        APIMonetizationInfoDTO body = null;
        api.apisApiIdMonetizePost(apiId, body);

        // TODO: test validations
    }
    
    /**
     * Get total revenue details of a given monetized API with meterd billing.
     *
     * This operation can be used to get details of total revenue details of a given monetized API with meterd billing. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apisApiIdRevenueGetTest() throws ApiException {
        String apiId = null;
        APIRevenueDTO response = api.apisApiIdRevenueGet(apiId);

        // TODO: test validations
    }
    
    /**
     * Get details of a pending invoice for a monetized subscription with meterd billing.
     *
     * This operation can be used to get details of a pending invoice for a monetized subscription with meterd billing. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void subscriptionsSubscriptionIdUsageGetTest() throws ApiException {
        String subscriptionId = null;
        APIMonetizationUsageDTO response = api.subscriptionsSubscriptionIdUsageGet(subscriptionId);

        // TODO: test validations
    }
    
}
