/*
 * WSO2 API Manager - Publisher API
 * This specifies a **RESTful API** for WSO2 **API Manager** - Publisher.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.rest.integration.tests.publisher.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * LifecycleStateInputBeanList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-07T02:17:03.896Z")
public class LifecycleStateInputBeanList {
  @SerializedName("name")
  private String name = null;

  @SerializedName("isRequired")
  private Boolean isRequired = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("placeHolder")
  private String placeHolder = null;

  @SerializedName("tooltip")
  private String tooltip = null;

  @SerializedName("regex")
  private String regex = null;

  @SerializedName("values")
  private String values = null;

  @SerializedName("forTarget")
  private String forTarget = null;

  public LifecycleStateInputBeanList name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "Gateways to be published", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LifecycleStateInputBeanList isRequired(Boolean isRequired) {
    this.isRequired = isRequired;
    return this;
  }

   /**
   * Get isRequired
   * @return isRequired
  **/
  @ApiModelProperty(example = "true", value = "")
  public Boolean getIsRequired() {
    return isRequired;
  }

  public void setIsRequired(Boolean isRequired) {
    this.isRequired = isRequired;
  }

  public LifecycleStateInputBeanList label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public LifecycleStateInputBeanList placeHolder(String placeHolder) {
    this.placeHolder = placeHolder;
    return this;
  }

   /**
   * Get placeHolder
   * @return placeHolder
  **/
  @ApiModelProperty(value = "")
  public String getPlaceHolder() {
    return placeHolder;
  }

  public void setPlaceHolder(String placeHolder) {
    this.placeHolder = placeHolder;
  }

  public LifecycleStateInputBeanList tooltip(String tooltip) {
    this.tooltip = tooltip;
    return this;
  }

   /**
   * Get tooltip
   * @return tooltip
  **/
  @ApiModelProperty(value = "")
  public String getTooltip() {
    return tooltip;
  }

  public void setTooltip(String tooltip) {
    this.tooltip = tooltip;
  }

  public LifecycleStateInputBeanList regex(String regex) {
    this.regex = regex;
    return this;
  }

   /**
   * Get regex
   * @return regex
  **/
  @ApiModelProperty(value = "")
  public String getRegex() {
    return regex;
  }

  public void setRegex(String regex) {
    this.regex = regex;
  }

  public LifecycleStateInputBeanList values(String values) {
    this.values = values;
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  @ApiModelProperty(value = "")
  public String getValues() {
    return values;
  }

  public void setValues(String values) {
    this.values = values;
  }

  public LifecycleStateInputBeanList forTarget(String forTarget) {
    this.forTarget = forTarget;
    return this;
  }

   /**
   * Get forTarget
   * @return forTarget
  **/
  @ApiModelProperty(example = "Created", value = "")
  public String getForTarget() {
    return forTarget;
  }

  public void setForTarget(String forTarget) {
    this.forTarget = forTarget;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LifecycleStateInputBeanList lifecycleStateInputBeanList = (LifecycleStateInputBeanList) o;
    return Objects.equals(this.name, lifecycleStateInputBeanList.name) &&
        Objects.equals(this.isRequired, lifecycleStateInputBeanList.isRequired) &&
        Objects.equals(this.label, lifecycleStateInputBeanList.label) &&
        Objects.equals(this.placeHolder, lifecycleStateInputBeanList.placeHolder) &&
        Objects.equals(this.tooltip, lifecycleStateInputBeanList.tooltip) &&
        Objects.equals(this.regex, lifecycleStateInputBeanList.regex) &&
        Objects.equals(this.values, lifecycleStateInputBeanList.values) &&
        Objects.equals(this.forTarget, lifecycleStateInputBeanList.forTarget);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, isRequired, label, placeHolder, tooltip, regex, values, forTarget);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LifecycleStateInputBeanList {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isRequired: ").append(toIndentedString(isRequired)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    placeHolder: ").append(toIndentedString(placeHolder)).append("\n");
    sb.append("    tooltip: ").append(toIndentedString(tooltip)).append("\n");
    sb.append("    regex: ").append(toIndentedString(regex)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    forTarget: ").append(toIndentedString(forTarget)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

